source("http://bioconductor.org/biocLite.R")
biocLite("rhdf5")
library(rhdf5)
hd5filename="example.hd5"
created = h5createFile(hd5filename)
created = h5createGroup(hd5filename,"cost")
created = h5createGroup(hd5filename,"product")
h5ls(hd5filename)
A = matrix(seq(100),nrow=10,ncol=10)
h5write(obj=A,file=hd5filename,name="cost/A")
library(data.table)
dt =  data.table(1:100,seq(100),seq(100))
h5write(dt,hd5filename,"product/dt")
readDt = h5read(hd5filename,"product/dt")
