glibrary(stringr)
str_trim("    hello   ")
paste(c("hello",1),c("world",2),sep="-",collapse=">")
paste("hello","world",sep="-",collapse=">")
substr("123456789",1,2)
grep("h",c("hello help","yield","held"),value=TRUE)
grep("h",c("hello help","yield","held"))
sub("_","@","____hello____")
gsub("_","#strsplit("Hello.World","[.]")
","____hello____",)
tolower("HelloWorld")
