fileUrl  <- "https://data.baltimorecity.gov/api/views/k5ry-ef3g/rows.csv?accessType=DOWNLOAD"
download.file(fileUrl,destfile="./restaurant.csv")
restData  <- read.csv("./restaurant.csv")
head(restData,n=3)
tail(restData,n=3)
names(restData)
summary(restData)
summary(restData[,"Location.1"])
quantile(restData$councilDistrict,probs=c(0.5,0.75,0.95))
summary(restData$zipCode)
table(restData$zipCode,useNA="ifany")
table(restData$councilDistrict,restData$zipCode)
sum(is.na(restData$councilDistrict))
any(is.na(restData$councilDistrict))
all(restData$zipCode>0)
colSums(is.na(restData))
all(colSums(is.na(restData))==0)
table(restData$zipCode %in% c("21212","21213"))
library(sqldf)
sqldf("select count(zipCode) from restData where zipCode in (21212,21213)")
sqldf("select * from restData where zipCode in (21212,21213)")
data(UCBAdmissions)
DF = as.data.frame(UCBAdmissions)
summary(DF)
xt <- xtabs(Freq~Gender+Admit,data=DF)
warpbreaks$replicate <- rep(1:9,len=54)
xt <- xtabs(breaks ~ .,data=warpbreaks)
ftable(xt)#flat table

fakeData  <- rnorm(1e5)
object.size(fakeData)
print(object.size(fakeData),units="Mb")
